project:
  type: website
  output-dir: docs
website:
  title: "Dylan Freebairn-Smith"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - EnviSci.qmd
      - gis.qmd
      - envpol.qmd
  page-footer:
    background: light
    left: Copyright 2024, Dylan Freebairn-Smith
    right: This website is built with blood, sweat, and tears


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

