project:
  type: website
  output-dir: docs
website:
  title: "Dylan Freebairn-Smith"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - EnviSci.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

