project:
  type: website
  output-dir: docs
website:
  favicon: images/Logo maker project (1).png # NOTE: that the `favicon` is a `website` level option (not under `navbar`)
  navbar:
    title: "Dylan Freebairn-Smith"
    logo: images/Logo maker project (1).png
    logo-alt: "My Personal Logo"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - text: "UCSB Studies"
        menu:
          - EnviSci.qmd
          - gis.qmd
          - envpol.qmd
  page-footer:
    background: light
    left: Copyright 2024, Dylan Freebairn-Smith
    right: Hi!


format:
  html:
    theme: 
    - styles.scss
    - yeti
    mainfont: Teachers
    toc: true
    page-layout: full
    lightbox: true

editor: visual

