{
  "hash": "dac3c4579442fafd3cca1124e7890817",
  "result": {
    "markdown": "---\ntitle: \"blog post title\"\ndescription: \"blog post description (appears underneath the title in smaller text) which is included on the listing page\"\nauthor:\n  - name: Dylan Freebairn-Smith\n    url: https://dtfrees.github.io/\ndate: 06-01-2024\ncitation: \n  url: https://dtfrees.github.io/posts/2024-06-01-HW-3/\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\n---\n\n---\ntitle: \"Homework 3\"\nauthor: \"Dylan Freebairn-Smith\"\ndate: 2024-06-01\nformat: html\neditor: visual\ntoc: true\nexecute: \n  warning: false\n  message: false\n---\n\n\n### [Github Repo:]{.underline}\n\n<https://github.com/dtfrees/freebairnsmith-dylan_homework-03.git>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load in packages\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(here)\nlibrary(janitor)\nlibrary(ggplot2)\n\n#visualize pairs\nlibrary(GGally)\n\n#selecting models\nlibrary(MuMIn)\n\n#model predictions\nlibrary(ggeffects)\n\n#model tables\nlibrary(gtsummary)\nlibrary(flextable)\nlibrary(modelsummary)\nlibrary(tibble) # for adding rows manually\n\ndrought_exp <- read_xlsx(path = here(\"posts\", \"2024-06-01-HW-3\",\n                                     \"Valliere_etal_EcoApps_Data.xlsx\"),\n                         sheet = \"First Harvest\")\n```\n:::\n\n\n## Clean the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# cleaning\ndrought_exp_clean <- drought_exp %>% \n  clean_names() %>% # nicer column names\n  mutate(species_name = case_when( # adding column with species scientific names\n    species == \"ENCCAL\" ~ \"Encelia californica\", # bush sunflower\n    species == \"ESCCAL\" ~ \"Eschscholzia californica\", # California poppy\n    species == \"PENCEN\" ~ \"Penstemon centranthifolius\", # Scarlet bugler\n    species == \"GRICAM\" ~ \"Grindelia camporum\", # great valley gumweed\n    species == \"SALLEU\" ~ \"Salvia leucophylla\", # Purple sage\n    species == \"STIPUL\" ~ \"Nasella pulchra\", # Purple needlegrass\n    species == \"LOTSCO\" ~ \"Acmispon glaber\" # deerweed\n  )) %>% \n  relocate(species_name, .after = species) %>% # moving species_name column after species\n  mutate(water_treatment = case_when( # adding column with full treatment names\n    water == \"WW\" ~ \"Well watered\",\n    water == \"DS\" ~ \"Drought stressed\"\n  )) %>% \n  relocate(water_treatment, .after = water) # moving water_treatment column after water\n```\n:::\n\n\n## Run Models\n\n#### model0: Null model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel0 <- lm(total_g ~ 1, # formula\n             data = drought_exp_clean) # data frame\n```\n:::\n\n\n#### model1: Total biomass as a function of SLA, water treatment, and species\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# saturated model\nmodel1 <- lm(total_g ~ sla + water_treatment + species_name,\n             data = drought_exp_clean)\n```\n:::\n\n\n#### model2: Total biomass as a function of SLA and water treatment\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(total_g ~ sla + water_treatment,\n             data = drought_exp_clean)\n```\n:::\n\n\n#### model3: Total biomass as a function of SLA and species\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(total_g ~ sla + species_name,\n             data = drought_exp_clean)\n```\n:::\n\n\n#### model4: Total biomass as a function of water treatment and species\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4 <- lm(total_g ~ water_treatment + species_name,\n             data = drought_exp_clean)\n```\n:::\n\n\n### Model selection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.sel(model0,\n          model1, \n          model2, \n          model3,\n          model4)\n```\n:::\n\n\n## Problem 1\n\n### a. Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a manual tibble to add the AIC delta to the table\nrows <- tribble(\n  ~term, ~null, ~\"model 1\", ~\"model 2\", ~\"model 3\", ~\"model 4\",\n  'AIC ∆', '81.22','2.44',  '60.37','32.12', '0.00'\n)\nattr(rows, 'position') <- c(20) # put the new row in the 20th row of the table\n\n# Comparing models\nmodelsummary <- modelsummary::modelsummary( # this function takes a list of models\n  list( \n    \"Null\" = model0, # \"model name\" = model object\n    \"Model 1\" = model1,\n    \"Model 2\" = model2,\n    \"Model 3\" = model3,\n    \"Model 4\" = model4\n  ),\n  add_rows = rows, # add the manually made tibble to the table\n  gof_map = c(\"r.squared\", \"aic\"), # only include the r squared and aic in the goodness of fit stats\n  title = \"Table 1: Linear Regression of Effect of SLA, Water Treatment, and Various Plant Species on Total Biomass\", # add a title\n  statistic = c(\"p = {p.value}\"), # make only p-value statistics added to the table\n  output = \"flextable\", # make the output table a flextable so it can be edited as one\n  stars = TRUE # add stars to statistically significant values\n)\n\n# Customize the flextable\nmodelsummary <- modelsummary %>% \n  autofit() %>% # make the spacing of the columns reasonable\n  border_inner_v() %>% # make vertical lines in between the cells\n  border_inner_h() %>% # make horizontal lines in between the cells\n  bg(i = c(1,3,5,7,9,11,13,15,17,19:21), bg = \"grey\") %>% # make the background of certain rows grey\n  bold(part = \"header\") %>%  # make the headers of the columns bold\n  set_caption(caption = \"Table 1: Linear Model of Effect of SLA, Water Treatment, and Various Plant Species on Total Biomass\")\n```\n:::\n\n\nTable 1: The columns are defined by the different and each row shows a differnet predictor variable estimate and the p-value ($\\alpha = 0.05$) below it. The Null model has none of the predictor values. The saturated model with all predictor variables is Model 1 (F(8, 61) = 23.44, p-val \\< 0.001, $\\alpha = 0.05$, $R^2 = 0.7545$). Model 2 (F(2, 67) = 14.57, p-val \\< 0.001, $\\alpha = 0.05$, $R^2 = 0.3031$), Model 3 (F(7, 62) = 13.85, p-val \\< 0.001, $\\alpha = 0.05$, $R^2 = 0.61$), and Model 4 (F(7, 62) = 27.08, p-val \\< 0.001, $\\alpha = 0.05$, $R^2 = 0.7535$) each have some other combination of Specific Leaf Area (sla), Water-treatment, and Species Type.\n\n#### Table 1: Linear Regression of Effect of SLA, Water Treatment, and Various Plant Species on Total Biomass\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-68a47ca8{}.cl-6899c11e{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6899c128{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-689d8038{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-689d9d20{width:3.113in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d2a{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d2b{width:0.927in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d34{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d35{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d3e{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d3f{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d48{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d49{width:3.113in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d4a{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d52{width:0.927in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d53{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d54{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d55{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d5c{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d5d{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d5e{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d5f{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d66{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d70{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d71{width:3.113in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d72{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d7a{width:0.927in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d7b{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d84{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d85{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d86{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d8e{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d8f{width:3.113in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d90{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d91{width:0.927in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d98{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d99{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d9a{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9d9b{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9da2{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9da3{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9da4{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dac{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dad{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dae{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9db6{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9db7{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9db8{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dc0{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dc1{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dc2{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dca{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dd4{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dd5{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dde{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9ddf{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9de8{width:3.113in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9de9{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9df2{width:0.927in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9df3{width:1.016in;background-color:rgba(190, 190, 190, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9df4{width:3.113in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9df5{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dfc{width:0.927in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-689d9dfd{width:1.016in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-68a47ca8'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-689d9d20\"><p class=\"cl-689d8038\"><span class=\"cl-6899c11e\"> </span></p></th><th class=\"cl-689d9d2a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c11e\">Null</span></p></th><th class=\"cl-689d9d2a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c11e\">Model 1</span></p></th><th class=\"cl-689d9d2b\"><p class=\"cl-689d8038\"><span class=\"cl-6899c11e\">Model 2</span></p></th><th class=\"cl-689d9d2a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c11e\">Model 3</span></p></th><th class=\"cl-689d9d34\"><p class=\"cl-689d8038\"><span class=\"cl-6899c11e\">Model 4</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d35\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">(Intercept)</span></p></td><td class=\"cl-689d9d3e\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.279***</span></p></td><td class=\"cl-689d9d3e\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.080</span></p></td><td class=\"cl-689d9d3f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.047</span></p></td><td class=\"cl-689d9d3e\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">-0.033</span></p></td><td class=\"cl-689d9d48\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.055*</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d49\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.162</span></p></td><td class=\"cl-689d9d52\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.394</span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.620</span></p></td><td class=\"cl-689d9d53\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.030</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d54\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">sla</span></p></td><td class=\"cl-689d9d55\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d55\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.000</span></p></td><td class=\"cl-689d9d5c\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.001**</span></p></td><td class=\"cl-689d9d55\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.001*</span></p></td><td class=\"cl-689d9d5d\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d49\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.619</span></p></td><td class=\"cl-689d9d52\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.001</span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.018</span></p></td><td class=\"cl-689d9d53\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d5e\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">water_treatmentWell watered</span></p></td><td class=\"cl-689d9d5f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d5f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.122***</span></p></td><td class=\"cl-689d9d66\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.090**</span></p></td><td class=\"cl-689d9d5f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d70\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.117***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d71\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d72\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d72\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d7a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.003</span></p></td><td class=\"cl-689d9d72\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d7b\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d84\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">species_nameEncelia californica</span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.238***</span></p></td><td class=\"cl-689d9d86\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.115+</span></p></td><td class=\"cl-689d9d8e\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.218***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d49\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d52\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.056</span></p></td><td class=\"cl-689d9d53\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d84\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">species_nameEschscholzia californica</span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.234***</span></p></td><td class=\"cl-689d9d86\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.222***</span></p></td><td class=\"cl-689d9d8e\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.232***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d8f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d91\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d98\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d99\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">species_nameGrindelia camporum</span></p></td><td class=\"cl-689d9d9a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d9a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.330***</span></p></td><td class=\"cl-689d9d9b\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d9a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.226***</span></p></td><td class=\"cl-689d9da2\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.313***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d8f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d91\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d98\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9da3\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">species_nameNasella pulchra</span></p></td><td class=\"cl-689d9da4\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9da4\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.241***</span></p></td><td class=\"cl-689d9dac\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9da4\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.168***</span></p></td><td class=\"cl-689d9dad\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.229***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d8f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d91\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d98\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d84\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">species_namePenstemon centranthifolius</span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.061</span></p></td><td class=\"cl-689d9d86\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d85\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">-0.006</span></p></td><td class=\"cl-689d9d8e\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.050</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d49\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.125</span></p></td><td class=\"cl-689d9d52\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d4a\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.896</span></p></td><td class=\"cl-689d9d53\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.128</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9dae\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">species_nameSalvia leucophylla</span></p></td><td class=\"cl-689d9db6\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9db6\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.117***</span></p></td><td class=\"cl-689d9db7\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9db6\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.139**</span></p></td><td class=\"cl-689d9db8\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.120***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9d8f\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td><td class=\"cl-689d9d91\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\"></span></p></td><td class=\"cl-689d9d90\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = 0.001</span></p></td><td class=\"cl-689d9d98\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">p = &lt;0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9dc0\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">R2</span></p></td><td class=\"cl-689d9dc1\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.000</span></p></td><td class=\"cl-689d9dc1\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.755</span></p></td><td class=\"cl-689d9dc2\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.303</span></p></td><td class=\"cl-689d9dc1\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.610</span></p></td><td class=\"cl-689d9dca\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.754</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9dd4\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">AIC ∆</span></p></td><td class=\"cl-689d9dd5\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">81.22</span></p></td><td class=\"cl-689d9dd5\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">2.44</span></p></td><td class=\"cl-689d9dde\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">60.37</span></p></td><td class=\"cl-689d9dd5\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">32.12</span></p></td><td class=\"cl-689d9ddf\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">0.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-689d9de8\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">AIC</span></p></td><td class=\"cl-689d9de9\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">-75.2</span></p></td><td class=\"cl-689d9de9\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">-157.5</span></p></td><td class=\"cl-689d9df2\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">-96.4</span></p></td><td class=\"cl-689d9de9\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">-127.1</span></p></td><td class=\"cl-689d9df3\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">-159.2</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"6\"class=\"cl-689d9df4\"><p class=\"cl-689d8038\"><span class=\"cl-6899c128\">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>\n```\n:::\n:::\n\n\n### b. Write a 5-6 sentence “statistical methods” section.\n\nTo analyze the influence of Specific Leaf Area (SLA), Species Type, and water treatment on total biomass of plant roots and shoots. We used five different linear regression models. These included a null model with no predictors (**model 0**)(, a saturated model with all three predictors (**model 1**),a model with SLA and water treatment (**model 2**), a model with SLA and Species Type (**model 3**), and a model with water treatment and Species Type (**model 4**). To choose the final model that best predicts the total biomass and is the least complex, we used the Akaike Information Criterion (AIC). **Model 4** (water treatment and Species Type) had the lowest AIC (-159.2) and was therefore the best model to use. I then plotted and analyzed the diagnostics of **Model 4**, where I visually assessed that the residuals were homoscedastic, normally distributed and outliers were not an issue.\n\n### c. Visualization\n\n#### Model predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_preds <- ggpredict(model4, \n                         terms = c(\n                                   \"water_treatment\", \n                                   \"species_name\"))\n\n# use View(model_preds) to see the predictions as a data frame\n# use model_preds to see the predictions formatted nicely\n\nView(model_preds)\n```\n:::\n\n\n#### Visualization code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# creating new data frame of model predictions for plotting\nmodel_preds_for_plotting <- model_preds %>% \n  rename(# renaming columns to make this easier to use\n         water_treatment = x,\n         species_name = group)\n\n# use View(model_preds_for_plotting) \n# to compare this to the original model_preds data frame\n\nggplot() +\n  # underlying data\n  geom_jitter(data = drought_exp_clean, # use original clean data for underlying points\n              aes(x = water_treatment, # water treatment on the x axis\n                  y = total_g, #total biomass on the y axis\n                  color = water_treatment), # color the points by water treatment\n              alpha = 0.3,  # make underlying data transparent\n              width = 0.1,  # make the underlying data jittered horizontally\n              height = 0) + # make the underlying data have no vertical jitter\n  # show points in underlying data\n  geom_point(data = model_preds_for_plotting, # use the model predictions\n             aes(x = water_treatment, \n                 y = predicted, # predicted total_g on the y axis\n                 color = water_treatment)) +\n     # model prediction 95% CI errorbar\n  geom_errorbar(data = model_preds_for_plotting,\n              aes(x = water_treatment,\n                  y = predicted,\n                  ymin = conf.low, #use the confidence interval in the model_preds df\n                  ymax = conf.high),\n              alpha = 0.2) + # decrease opacity\n  # cleaner theme\n  theme_classic() + \n  # no legend\n  theme(legend.position = \"none\") + \n  # creating different panels for each species\n  facet_wrap(~ species_name) +\n  # change colors\n  scale_color_manual(values = c(\"Well watered\" = \"#afe67c\", \n                                \"Drought stressed\" = \"#cab90df0\")) +\n  # labels\n  labs(title = \"Chart 1: Predicted Response by Species and Water Treatment\", # titles\n       x = \"Water Treatment ~ Species\",\n       y = \"Total Biomass (g)\",\n       caption = \"Chart 1: This plot shows the output of a linear regression model \n       predicting how the total mass of a plant can be predicted by species type\n       and water treatment. Each species has a separate plot with the data for\n       the totalbiomass of the species for both water treatments.\n       Data citation: Valliere, Justin; Zhang,Jacqueline; Sharifi,\n       M.; Rundel, Philip (2019). Data from: Can we condition native\n       plants to increase drought tolerance and improve restoration\n       success? Dataset. Dryad. https://doi.org/10.5061/dryad.v0861f7\n       \") # caption\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n### d.Write a caption for your visualization.\n\nCaption in figure above.\n\nChart 1: Predicted Response by Species and Water Treatment: This plot shows the output of a linear regression model predicting how the total mass of a plant can be predicted by species type and water treatment. Each species has a separate plot with the data for the total biomass of the species for both water treatments.\n\nData citation: Valliere, Justin; Zhang,Jacqueline; Sharifi, M.; Rundel, Philip (2019). Data from: Can we condition native plants to increase drought tolerance and improve restoration success? Dataset. Dryad. <https://doi.org/10.5061/dryad.v0861f7>\n\n### e. Write a 3-4 sentence results section.\n\nModel 4 with predictors Species type and water treatment had the best prediction of the total biomass. (F(7, 62) = 27.08, p-val \\< 0.001, $\\alpha = 0.05$, $R^2 = 0.7535$) (AIC = -159.2). On average, the total biomass of Well watered plants were 0.117 ± 0.017g heavier than drought treated plants (p \\< 0.001). On average, the total biomass across species was 0.279 ± 0.025g heavier than drought-treated Acmispon glaber plants (all p \\< 0.001 except for Penstemon centranthifolius).\n\n## **Problem 2**\n\n### a. Describe in words what an affective visualization could look like for your personal data\n\nI have a number of different predictor variables that I was looking at to see if they influenced my plunge time. I think I want to look at how the air temp and weather type affected my plunge time. I am thinking of doing a thermometer with temps labelled on one side and then symbols representing different time spent plunging classifications and then something to add to those symbols to represent weather type. These symbols will stack horizontally to from left to right.\n\n### b. Inital Affective Data Viz\n\n![Sketch](images/IMG_0945.jpg){fig-align=\"center\" width=\"2016\"}\n\n### c. Draft Affective Data Viz\n\n![Draft](images/IMG_0947.jpg){fig-align=\"center\" width=\"2016\"}\n\n### d. Artist statement.\n\nIn this piece, I am showing how my time spent cold plunging varies over different air temps and weather types. Each circle represents one cold plunge and hwo filled in it is represents the amount of time spent in the water during that cold plunge. I drew a lot of inspiration from [Stefanie Posavec and Giorgia Lupi’s Dear Data project](https://www.dear-data.com/all). This is just an initial pencil skecth but I will put colors into this sketch to make the piece more attractive. I spent a lot of time brain storming which variables to use and how to use them.\n\n## Problem 3\n\n[An assessment of the effectiveness of Marine Protected Areas in the San Juan Islands, Washington, USA](https://doi.org/10.1006/jmsc.2000.0808)\n\n### a. Revisit and Summarize \n\nThe authors used Principal Component Analysis (PCA), One-Way Analysis of Variance (ANOVA), and a Pearson product-moment correlation matrix. The PCA was used to explore site and species relationships. The ANOVA was used to see the significance of each variable that had an influence on the clustering of the sites and species. Finally, the correlation matrix was used to find relationships between abiotic variables.\n\n![Source: Tuya et al., 2000](images/stat_crit.png)\n\n### b. Visual Clarity\n\nI think the authors did a good job representing their One-Way ANOVA statistics clearly relative to the complexity of their analyses. The x and y axis are in a logical position; however I think they could have had less intervals on the y-axis because it is not very clear on the units of density and I think what matters much more is to show if the density are relatively higher or lower. They did not do a great job showing underlying data or summary statistics. The bar-and-whisker plot leaves out any underlying data and does not show the low end of the SE or CI whisker (it did not specify what the whisker represented).\n\n### c. Aesthetic clarity\n\nI think that the authors had a balanced data:ink ratio; none of the ink was pointless. The only extraneous info that I would have taken out would have been to thin the intervals on the y-axis. There are the borders around the plots and the filled in bars which are extra ink, but I think that they are useful in differentiating the space and showing which statistics were significant and which one weren't. To lessen the amount of ink on the page they could possibly use hatching instead of a complete fill on the bars.\n\n### d. Recommendations\n\nMy first recommendation would be to create fewer intervals on the y-axis because I don't think the main message of the figure is enhanced at all by more specificity of the density of the urchins. My second recommendation would be to add the underlying data of the different urchin densities across sites and sizes. I would do this by adding a jitter plot of these points faceted and grouped in the same way the bars are. I would also keep the current coloring by having the small urchin data points a different color than the other ones, but put the coloring on on the jittered points. If they did not want jittered points I would recommend to hatch the bars instead of filling them to help the data:ink ratio. Finally, I would also add a mean point and 95% Confidence Interval error bar in place of the bar-and-whisker, this would show the underlying data and the low end of the CI.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}